Sac/Models/Chamado.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chamado
    {
        public int IdChamado { get; set; }
        public System.DateTime DataAbertura { get; set; }
        public string Descricao { get; set; }
        public int IdCliente { get; set; }
        public string Estado { get; set; }
        public string Urgencia { get; set; }
        public Nullable<int> IdAtendente { get; set; }
        public string Solucao { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}

Sac/Controllers/ChamadoController.cs
using Sac.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Sac.Controllers
{
    public class ChamadoController : Controller
    {

        private sacEntities db = new sacEntities();


        public async Task<ActionResult> Index(string estado)
        {

            BindUrgencia();
            BindEstado();

            IQueryable<Chamado> chamado;

            if (User.IsInRole("Administrador") || User.IsInRole("Atendente"))
            {
                chamado = db.Chamado.Include(c => c.Usuario)
                                        .Include(c => c.Usuario1);
            }
            else
            {
                chamado = db.Chamado.Include(c => c.Usuario)
                                         .Include(c => c.Usuario1)
                                         .Where(c => c.Usuario1.UserName == User.Identity.Name);
            }


            if (!string.IsNullOrEmpty(estado) && estado != "Todos")
            {
                chamado = db.Chamado.Where(x => x.Estado == estado);
            }


            return View(await chamado.ToListAsync());
        }

        // GET: Chamado/Details/5

        [Authorize(Roles = "Atendente")]
        public async Task<ActionResult> Solucionar(int? id)
        {
            BindUrgencia();
            BindEstado();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chamado chamado = await db.Chamado.FindAsync(id);
            if (chamado == null)
            {
                return HttpNotFound();
            }
            return View(chamado);
        }
        [Authorize(Roles = "Atendente")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Solucionar(int? id, string Solucao)
        {

            BindUrgencia();
            BindEstado();

            var chamado = await db.Chamado.FindAsync(id);
            chamado.Solucao = Solucao;

                var usuario = await db.Usuario.Where(u => u.UserName == User.Identity.Name).FirstAsync();
                chamado.IdAtendente = usuario.IdUsuario;

            chamado.Estado = "Finalizado";

            if (ModelState.IsValid && !string.IsNullOrWhiteSpace(chamado.Solucao))
            {
                db.Entry(chamado).State = EntityState.Modified;
                await db.SaveChangesAsync();
                BindUrgencia();
                BindEstado();
                return RedirectToAction("Index");
            }

           

            ModelState.AddModelError("", "Solução é obrigatória!");
            ViewBag.IdAtendente = new SelectList(db.Usuario, "IdUsuario", "Nome", chamado.IdAtendente);
            ViewBag.IdCliente = new SelectList(db.Usuario, "IdUsuario", "Nome", chamado.IdCliente);

            return View(chamado);
        }
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chamado chamado = await db.Chamado.FindAsync(id);
            if (chamado == null)
            {
                return HttpNotFound();
            }

            BindUrgencia();
            BindEstado();
            return View(chamado);
        }


        private void BindUrgencia()
        {
            List<SelectListItem> items = new List<SelectListItem>();

            items.Add(new SelectListItem { Text = "Simples", Value = "Simples" });

            items.Add(new SelectListItem { Text = "Moderada", Value = "Moderado" });            

            items.Add(new SelectListItem { Text = "Grave", Value = "Grave" });

            ViewBag.Urgencia = items;
        }



        private void BindEstado()
        {
            List<SelectListItem> items = new List<SelectListItem>();

            items.Add(new SelectListItem { Text = "Pendente", Value = "Pendente" });

            items.Add(new SelectListItem { Text = "Aguardando", Value = "Aguardando" });

            items.Add(new SelectListItem { Text = "Finalizado", Value = "Finalizado" });

            ViewBag.Estado = items;
        }


        // GET: Chamado/Create
        public ActionResult Create()
        {
      
            BindUrgencia();
            BindEstado();
            ViewBag.IdAtendente = new SelectList(db.Usuario, "IdUsuario", "Nome");
            ViewBag.IdCliente = new SelectList(db.Usuario, "IdUsuario", "Nome");
            return View();
        }

        // POST: Chamado/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create( Chamado chamado)
        {
            chamado.DataAbertura = DateTime.Now;
            chamado.Estado = "Aguardando";

            var usuario = await db.Usuario.Where(u => u.UserName == User.Identity.Name).FirstAsync();
            chamado.IdCliente = usuario.IdUsuario;
        

            if (ModelState.IsValid)
            {

       
                db.Chamado.Add(chamado);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.IdAtendente = new SelectList(db.Usuario, "IdUsuario", "Nome", chamado.IdAtendente);
            ViewBag.IdCliente = new SelectList(db.Usuario, "IdUsuario", "Nome", chamado.IdCliente);
            return View(chamado);
        }

        // GET: Chamado/Edit/5
        [Authorize(Roles = "Administrador")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Chamado chamado = await db.Chamado.FindAsync(id);
            if (chamado == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdAtendente = new SelectList(db.Usuario, "IdUsuario", "Nome", chamado.IdAtendente);
            ViewBag.IdCliente = new SelectList(db.Usuario, "IdUsuario", "Nome", chamado.IdCliente);
            BindUrgencia();
            BindEstado();
            return View(chamado);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador")]
        public async Task<ActionResult> Edit(int id ,Chamado chamado)
        {

            var domain = db.Chamado.Where(x => x.IdChamado == id).SingleOrDefault();

            domain.Estado = chamado.Estado;
            domain.Descricao = chamado.Descricao;
            domain.Solucao = chamado.Solucao;
            domain.Urgencia = chamado.Urgencia;


            if (ModelState.IsValid)
            {
                db.Entry(domain).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.IdAtendente = new SelectList(db.Usuario, "IdUsuario", "Nome", chamado.IdAtendente);
            ViewBag.IdCliente = new SelectList(db.Usuario, "IdUsuario", "Nome", chamado.IdCliente);
            BindUrgencia();
            BindEstado();
            return View(chamado);
        }

        [Authorize(Roles = "Cliente")]
        public async Task<ActionResult> FecharChamado(int? id)
        {
            var chamado = await db.Chamado.FindAsync(id);
            chamado.Estado = "Finalizado";

            db.Entry(chamado).State = EntityState.Modified;
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    }
}

Sac/Views/Chamado/Create.cshtml
@model Sac.Models.Chamado

@{
    ViewBag.Title = "Novo chamado";
}

<h2>Novo chamado</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Urgencia, "Urgência", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(x => x.Urgencia, new SelectList(ViewBag.Urgencia, "Value", "Text"), new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Urgencia, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Sac/Views/Chamado/Details.cshtml
@model Sac.Models.Chamado

@{
    ViewBag.Title = "Detalhes do chamado";
}

<h2>Detalhes do chamado</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DataAbertura)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataAbertura)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Solucao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Solucao)
        </dd>

        

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Urgencia)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Urgencia)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Usuario.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuario.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Usuario1.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Usuario1.Nome)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IdChamado }) |
    @Html.ActionLink("Voltar", "Index")
</p>

Sac/Views/Chamado/Edit.cshtml
@model Sac.Models.Chamado

@{
    ViewBag.Title = "Editar chamado";
}

<h2>Editar chamado</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdChamado)

        <div class="form-group">
            @Html.LabelFor(model => model.DataAbertura, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataAbertura, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataAbertura, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdCliente, "IdCliente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdCliente", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdCliente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, "Estado", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Estado", new SelectList(ViewBag.Estado, "Value", "Text"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Urgencia, "Urgencia", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Urgencia", new SelectList(ViewBag.Urgencia, "Value","Text"), htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Urgencia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdAtendente, "IdAtendente", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdAtendente", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdAtendente, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Solucao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Solucao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Solucao, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gravar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Sac/Views/Chamado/Index.cshtml
@model IEnumerable< Sac.Models.Chamado >

@{
    ViewBag.Title = "Chamados";
}

<h2>Chamados</h2>

<p>
    @Html.ActionLink("Novo chamado", "Create")
</p>
<div class="form-inline">
    @using (Html.BeginForm("Index", "Chamado", FormMethod.Get))
    {
        @Html.Label("Estado:")

        <select name="estado" class="form-control">
            <option value="null">Todos</option>
            @foreach (var estado in ViewBag.Estado)
            {
                if (Request.QueryString["Estado"] == estado.Value)
                {
                    <option value="@estado.Value" selected="selected">@estado.Value</option>
                }
                else
                {
                    <option value="@estado.Value">@estado.Value</option>
                }
            }
        </select>

      
        <input type="submit" value="Filtrar" class="btn btn-default" />
    }
</div>
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DataAbertura)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Solucao)
        </th>
     
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Urgencia)
        </th>

        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DataAbertura)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Solucao)
        </td>
     
        <td>
            @Html.DisplayFor(modelItem => item.Estado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Urgencia)
        </td>
        <td>
            @if (User.IsInRole("Administrador"))
            {
                @Html.ActionLink("Editar", "Edit", new { id = item.IdChamado }) <span>|</span>                
                @Html.ActionLink("Detalhes", "Details", new { id = item.IdChamado })
            }
            @if (User.IsInRole("Atendente") && item.Estado == "Aguardando")
            {
                @Html.ActionLink("Solucionar", "Solucionar", new { id = item.IdChamado })
            }
            @if (User.IsInRole("Cliente") && item.Estado == "Pendente")
            {
                @Html.ActionLink("Fechar", "FecharChamado", new { id = item.IdChamado })
            }
        </td>
    </tr>
}

</table>

Sac/Views/Chamado/Solucionar.cshtml
@model Sac.Models.Chamado

@{
    ViewBag.Title = "Solucionar chamado";
}

<h2>Solucionar chamado</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })








        <div class="form-group">
            @Html.LabelFor(model => model.Solucao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Solucao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Solucao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Gravar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>