Sac/Models/Usuario.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Chamado = new HashSet<Chamado>();
            this.Chamado1 = new HashSet<Chamado>();
        }
    
        public int IdUsuario { get; set; }
        public string Nome { get; set; }
        public string Email { get; set; }
        public string Telefone { get; set; }
        public string UserName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chamado> Chamado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chamado> Chamado1 { get; set; }
    }
}

Sac/Models/UsuarioViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Sac.Models
{
    public class UsuarioViewModel
    {
        [Required(ErrorMessage = "O nome é obrigatório")]
        public string Nome { get; set; }

        [DisplayName("E-mail")]
        [Required(ErrorMessage = "O e-mail é obrigatório")]
        public string Email { get; set; }

   

        [DisplayName("Usuário")]
        [Required(ErrorMessage = "O login é obrigatório")]
        public string Username { get; set; }

        [DisplayName("Senha")]
        [Required(ErrorMessage = "A senha é obrigatória")]
        [DataType(DataType.Password)]
        public string Senha { get; set; }
        [DataType(DataType.Password)]

        [DisplayName("Confirmação senha")]
        [Required(ErrorMessage = "A confirmação de senha é obrigatória")]
        [Compare("Senha", ErrorMessage = "A senha e a confirmação não conferem! Digite novamente!")]
        public string Confirma { get; set; }

        [Required(ErrorMessage = "O papel é obrigatório")]
        public string Papel { get; set; }


    }
}

Sac/Controllers/AutenticacaoController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using Sac.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Sac.Controllers
{
    public class AutenticacaoController : Controller
    {
        // GET: Autenticacao
        private sacEntities db = new sacEntities();


        private void CarregaRoles()
        {
            var roleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>());
            var lista = roleManager.Roles.ToList();

            ViewBag.Roles = new SelectList(lista, "Id", "Name");
        }

        // GET: Autenticacao
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

       //  [Authorize(Roles = "Administrador")]
        public ActionResult Criar()
        {
            CarregaRoles();
            return View();
        }


        [HttpPost]
        // [Authorize(Roles = "Administrador")]
        public async Task<ActionResult> Criar(UsuarioViewModel usuario)
        {
            if (!ModelState.IsValid)
            {
                CarregaRoles();
                return View(usuario);
            }
            else
            {
                var usuarioStore = new UserStore<IdentityUser>();
                var usuarioManager = new UserManager<IdentityUser>(usuarioStore);
                //Cria uma identidade
                var usuarioInfo = new IdentityUser()
                {
                    UserName = usuario.Username
                };

                //Cria o usuário
                IdentityResult resultado = usuarioManager.Create(usuarioInfo, usuario.Senha);
                //se o usuário foi criado, o autentica
                if (resultado.Succeeded)
                {

                    var identityUserRole = new IdentityUserRole();
                    identityUserRole.RoleId = usuario.Papel;
                    identityUserRole.UserId = usuarioInfo.Id;

                    usuarioInfo.Roles.Add(identityUserRole);

                    usuarioManager.Update(usuarioInfo);

                    var usuarioDb = new Usuario()
                    {
                        Nome = usuario.Nome,
                        Telefone = "",
                        Email = usuario.Email,
                        UserName = usuario.Username
                    };

                    db.Usuario.Add(usuarioDb);
                    await db.SaveChangesAsync();

                    return RedirectToAction("Index", "Usuario");
                }
                else
                {
                    CarregaRoles();
                    ModelState.AddModelError("", resultado.Errors.FirstOrDefault());
                    return View(usuario);
                }
            }
        }


        [HttpPost]
        public ActionResult Login(UsuarioViewModel usuario, string ReturnUrl)
        {
            if (string.IsNullOrWhiteSpace(usuario.Username) || string.IsNullOrWhiteSpace(usuario.Senha))
            {
                ModelState.AddModelError("", "Entre com o usuário e senha!");
                return View(usuario);
            }
            else
            {
                var usuarioStore = new UserStore<IdentityUser>();
                var usuarioManager = new UserManager<IdentityUser>(usuarioStore);
                var usuarioInfo = usuarioManager
                .Find(usuario.Username, usuario.Senha);
                if (usuarioInfo != null)
                {
                    var autManager = System.Web.HttpContext.Current.GetOwinContext().Authentication;
                    var identidadeUsuario = usuarioManager
                    .CreateIdentity(usuarioInfo,
                    DefaultAuthenticationTypes.ApplicationCookie);
                    autManager.SignIn(new AuthenticationProperties()
                    { IsPersistent = false }, identidadeUsuario);

                    if (ReturnUrl == null)
                    {
                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        return Redirect(ReturnUrl);
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Usuário/senha inválido!");
                    return View();
                }
            }
        }

        public ActionResult Logout()
        {
            var autManager = System.Web.HttpContext.Current.GetOwinContext().Authentication;
            autManager.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

Sac/Controllers/UsuarioController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Sac.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
namespace Sac.Controllers
    {
        //[Authorize(Roles = "Administrador")]
        public class UsuarioController : Controller
        {
            private sacEntities db = new sacEntities();

            // GET: Usuario
            public async Task<ActionResult> Index()
            {
                return View(await db.Usuario.ToListAsync());
            }

            // GET: Usuario/Details/5
            public async Task<ActionResult> Details(int? id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Usuario usuario = await db.Usuario.FindAsync(id);
                if (usuario == null)
                {
                    return HttpNotFound();
                }
                return View(usuario);
            }

            // GET: Usuario/Edit/5
            public async Task<ActionResult> Edit(int? id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Usuario usuario = await db.Usuario.FindAsync(id);
                if (usuario == null)
                {
                    return HttpNotFound();
                }
                return View(usuario);
            }

            // POST: Usuario/Edit/5
            // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
            // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<ActionResult> Edit([Bind(Include = "IdUsuario,Nome,Email,Telefone,UserName")] Usuario usuario)
            {
                try
                {
                    if (ModelState.IsValid)
                    {
                        using (var ctx = new sacEntities())
                        {
                            var usuarioOld = await ctx.Usuario.FindAsync(usuario.IdUsuario);
                            usuario.UserName = usuarioOld.UserName;
                            usuarioOld = null;
                        }

                        db.Entry(usuario).State = EntityState.Modified;
                        await db.SaveChangesAsync();
                        return RedirectToAction("Index");
                    }
                    return View(usuario);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", ex.Message);
                    return View(usuario);
                }
            }

            // GET: Usuario/Delete/5
            public async Task<ActionResult> Delete(int? id)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Usuario usuario = await db.Usuario.FindAsync(id);
                if (usuario == null)
                {
                    return HttpNotFound();
                }
                return View(usuario);
            }

            // POST: Usuario/Delete/5
            [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public async Task<ActionResult> DeleteConfirmed(int id)
            {
                Usuario usuario = await db.Usuario.FindAsync(id);

                if (User.Identity.Name == usuario.UserName)
                {
                    ModelState.AddModelError("", "Você não pode excluir o seu usuário!");
                    return View(usuario);
                }

                var result = await db.Chamado.Where(c => c.IdCliente == id || c.IdAtendente == id).ToListAsync();

                if (result.Count > 0)
                {
                    ModelState.AddModelError("", "Não pode excluir usuário com chamado atrelado!");
                    return View(usuario);
                }

                db.Usuario.Remove(usuario);
                await db.SaveChangesAsync();

                var usuarioStore = new UserStore<IdentityUser>();
                var _userManager = new UserManager<IdentityUser>(usuarioStore);

                var user = await _userManager.FindByNameAsync(usuario.UserName);
                var logins = user.Logins;
                var rolesForUser = await _userManager.GetRolesAsync(User.Identity.GetUserId());

                foreach (var login in logins.ToList())
                    await _userManager.RemoveLoginAsync(login.UserId, new UserLoginInfo(login.LoginProvider, login.ProviderKey));

                if (rolesForUser.Count() > 0)
                {
                    foreach (var item in rolesForUser.ToList())
                    {
                        await _userManager.RemoveFromRoleAsync(user.Id, item);
                    }
                }

                await _userManager.DeleteAsync(user);



                return RedirectToAction("Index");
            }

    

}
}

Sac/Views/Usuario/Delete.cshtml
@model Sac.Models.Usuario

@{
    ViewBag.Title = "Excluir usuário";
}

<h2>Excluir usuário</h2>

<div>
@using (Html.BeginForm())
{
    <hr />
    @Html.ValidationSummary(true, (string)ViewBag.Erro, new { @class = "text-danger" })
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

    </dl>

        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            @Html.ActionLink("Voltar", "Index")
        </div>
    }
</div>

Sac/Views/Usuario/Details.cshtml
@model Sac.Models.Usuario

@{
    ViewBag.Title = "Detalhes do usuário";
}

<h2>Detalhes do usuários</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.IdUsuario }) |
    @Html.ActionLink("Voltar", "Index")
</p>

Sac/Views/Usuario/Edit.cshtml
@model Sac.Models.Usuario

@{
    ViewBag.Title = "Editar usuário";
}

<h2>Editar usuário</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IdUsuario)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Sac/Views/Usuario/Index.cshtml
@model IEnumerable<Sac.Models.Usuario>

@{
    ViewBag.Title = "Lista de usuários";
}

<h2>Lista de usuários</h2>

<p>
    @Html.ActionLink("Novo usuário", "Criar", "Autenticacao")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
  
        <th>
            @Html.DisplayNameFor(model => model.UserName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
     
        <td>
            @Html.DisplayFor(modelItem => item.UserName)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id=item.IdUsuario }) |
            @Html.ActionLink("Detalhes", "Details", new { id=item.IdUsuario }) |
            @Html.ActionLink("Excluir", "Delete", new { id=item.IdUsuario })
        </td>
    </tr>
}

</table>